# Generated by Django 3.2.12 on 2022-02-07 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MvFactWeatherDaily',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('mean_daily_temp', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('median_daily_temp', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('min_daily_temp', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('max_daily_temp', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('transformation_name', models.CharField(blank=True, max_length=100, null=True)),
                ('transformation_dt', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mv_fact_weather_daily',
                'managed': False,
            },
        ),
    ]
